### ISSUE TITLE
Would be helpful to add in how to rename a branch ? 

### ISSUE THREAD

**Issue by dkunkel27** [mica-web/mica-web.github.io#10]
> **NOTE:** If you followed a link from the course web site, the title above should automatically include the URL for the page you were on. If not, please note the page URL here: 

### About this feedback
👀 I have identified:
* [ ] A broken link
* [ ] Content that is incorrect (including typos)
* [ ] Content that is confusing
* [ ] A layout/CSS bug
* [ ] Something else

### What needs to be fixed
> Describe the existing content. You can copy and paste the existing text or link here, for example.

### Possible solutions
> Let me know what would fix the current content.

### Additional context
> Anything else that would be helpful for me to know in order to fix this issue. If you're describing a layout or CSS bug, here it would be helpful to note your operating system and web browser. You can visit this link: http://supportdetails.net/ and copy the URL under "Share these details" to provide an extra-credit level of information. 🙏🏻

**Comment by angeliquejw** [comment]
@dkunkel27, thanks for this feedback! Let me know if [this update to the page](https://mica-web.github.io/learn/workflows/branching#renaming-your-branch) provides the info you were looking for?

**Comment by dkunkel27** [comment]
Yes this is super helpful—thank you!
