### ISSUE TITLE
Feedback for /learn/css/dimensions

### ISSUE THREAD

**Issue by dkunkel27** [mica-web/mica-web.github.io#13]
https://mica-web.github.io/learn/css/dimensions

where you mention the parent element,, what exactly is the parent element? Is that the overall box model it technically exists in?

**Comment by angeliquejw** [comment]
@dkunkel27, thanks for calling this out -- I've updated the page with more info here : https://mica-web.github.io/learn/css/dimensions

Let me know if this makes things clearer?
