### ISSUE TITLE
Feedback for /learn/tools/browsers

### ISSUE THREAD

**Issue by adworetzky** [mica-web/mica-web.github.io#6]
> **NOTE:** If you followed a link from the course web site, the title above should automatically include the URL for the page you were on. If not, please note the page URL here: 

### About this feedback
👀 I have identified:
* [x] A broken link
* [ ] Content that is incorrect (including typos)
* [ ] Content that is confusing
* [ ] A layout/CSS bug
* [ ] Something else

### What needs to be fixed
> Describe the existing content. You can copy and paste the existing text or link here, for example.
The breadcrumb link at the top titled "tools" is broken

### Possible solutions
> Let me know what would fix the current content.
Perhaps it's just a dead link or maybe the tools page doesn't exist yet?

### Additional context
> Anything else that would be helpful for me to know in order to fix this issue. If you're describing a layout or CSS bug, here it would be helpful to note your operating system and web browser. You can visit this link: http://supportdetails.net/ and copy the URL under "Share these details" to provide an extra-credit level of information. 🙏🏻

**Comment by angeliquejw** [comment]
Hi, @adworetzky -- Thanks for reporting this. My deploy this afternoon should hopefully fix this issue (but you may need to clear your browser cache to see the impact).

Let me know if the breadcrumbs now work as expected on your end. 👍🏻
